name: Jarvis Deployment
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Jarvis
    runs-on: ubuntu-latest
    steps:   
    - name: executing remote ssh commands using ssh key
      uses: actions/checkout@v2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: 22
        script: sh scripts/deployment/update_jarvis.sh
